use std::os::raw::c_void;


pub struct InstanceFunctions {
    pub v1_0: ash::vk::InstanceFnV1_0,
    pub v1_1: ash::vk::InstanceFnV1_1,
    pub v1_2: ash::vk::InstanceFnV1_2,
    pub v1_3: ash::vk::InstanceFnV1_3,
    pub khr_android_surface: ash::vk::KhrAndroidSurfaceFn,
    pub khr_device_group: ash::vk::KhrDeviceGroupFn,
    pub khr_device_group_creation: ash::vk::KhrDeviceGroupCreationFn,
    pub khr_display: ash::vk::KhrDisplayFn,
    pub khr_external_fence_capabilities: ash::vk::KhrExternalFenceCapabilitiesFn,
    pub khr_external_memory_capabilities: ash::vk::KhrExternalMemoryCapabilitiesFn,
    pub khr_external_semaphore_capabilities: ash::vk::KhrExternalSemaphoreCapabilitiesFn,
    pub khr_fragment_shading_rate: ash::vk::KhrFragmentShadingRateFn,
    pub khr_get_display_properties2: ash::vk::KhrGetDisplayProperties2Fn,
    pub khr_get_physical_device_properties2: ash::vk::KhrGetPhysicalDeviceProperties2Fn,
    pub khr_get_surface_capabilities2: ash::vk::KhrGetSurfaceCapabilities2Fn,
    pub khr_performance_query: ash::vk::KhrPerformanceQueryFn,
    pub khr_surface: ash::vk::KhrSurfaceFn,
    pub khr_swapchain: ash::vk::KhrSwapchainFn,
    pub khr_video_queue: ash::vk::KhrVideoQueueFn,
    pub khr_wayland_surface: ash::vk::KhrWaylandSurfaceFn,
    pub khr_win32_surface: ash::vk::KhrWin32SurfaceFn,
    pub khr_xcb_surface: ash::vk::KhrXcbSurfaceFn,
    pub khr_xlib_surface: ash::vk::KhrXlibSurfaceFn,
    pub ext_acquire_drm_display: ash::vk::ExtAcquireDrmDisplayFn,
    pub ext_acquire_xlib_display: ash::vk::ExtAcquireXlibDisplayFn,
    pub ext_calibrated_timestamps: ash::vk::ExtCalibratedTimestampsFn,
    pub ext_debug_report: ash::vk::ExtDebugReportFn,
    pub ext_debug_utils: ash::vk::ExtDebugUtilsFn,
    pub ext_direct_mode_display: ash::vk::ExtDirectModeDisplayFn,
    pub ext_directfb_surface: ash::vk::ExtDirectfbSurfaceFn,
    pub ext_display_surface_counter: ash::vk::ExtDisplaySurfaceCounterFn,
    pub ext_full_screen_exclusive: ash::vk::ExtFullScreenExclusiveFn,
    pub ext_headless_surface: ash::vk::ExtHeadlessSurfaceFn,
    pub ext_metal_surface: ash::vk::ExtMetalSurfaceFn,
    pub ext_sample_locations: ash::vk::ExtSampleLocationsFn,
    pub ext_tooling_info: ash::vk::ExtToolingInfoFn,
    pub fuchsia_imagepipe_surface: ash::vk::FuchsiaImagepipeSurfaceFn,
    pub ggp_stream_descriptor_surface: ash::vk::GgpStreamDescriptorSurfaceFn,
    pub mvk_ios_surface: ash::vk::MvkIosSurfaceFn,
    pub mvk_macos_surface: ash::vk::MvkMacosSurfaceFn,
    pub nn_vi_surface: ash::vk::NnViSurfaceFn,
    pub nv_cooperative_matrix: ash::vk::NvCooperativeMatrixFn,
    pub nv_coverage_reduction_mode: ash::vk::NvCoverageReductionModeFn,
    pub nv_external_memory_capabilities: ash::vk::NvExternalMemoryCapabilitiesFn,
    pub nv_optical_flow: ash::vk::NvOpticalFlowFn,
    pub qnx_screen_surface: ash::vk::QnxScreenSurfaceFn,
}

impl  InstanceFunctions {
    pub(crate) fn load<F>(mut load_fn: F) -> InstanceFunctions
    where
        F: FnMut(&core::ffi::CStr) -> *const c_void,
    {
        Self { 
            v1_0: ash::vk::InstanceFnV1_0::load(&mut load_fn), 
            v1_1: ash::vk::InstanceFnV1_1::load(&mut load_fn), 
            v1_2: ash::vk::InstanceFnV1_2::load(&mut load_fn), 
            v1_3: ash::vk::InstanceFnV1_3::load(&mut load_fn), 
            khr_android_surface: ash::vk::KhrAndroidSurfaceFn::load(&mut load_fn), 
            khr_device_group: ash::vk::KhrDeviceGroupFn::load(&mut load_fn), 
            khr_device_group_creation: ash::vk::KhrDeviceGroupCreationFn::load(&mut load_fn), 
            khr_display: ash::vk::KhrDisplayFn::load(&mut load_fn), 
            khr_external_fence_capabilities: ash::vk::KhrExternalFenceCapabilitiesFn::load(&mut load_fn), 
            khr_external_memory_capabilities: ash::vk::KhrExternalMemoryCapabilitiesFn::load(&mut load_fn), 
            khr_external_semaphore_capabilities: ash::vk::KhrExternalSemaphoreCapabilitiesFn::load(&mut load_fn), 
            khr_fragment_shading_rate: ash::vk::KhrFragmentShadingRateFn::load(&mut load_fn), 
            khr_get_display_properties2: ash::vk::KhrGetDisplayProperties2Fn::load(&mut load_fn), 
            khr_get_physical_device_properties2: ash::vk::KhrGetPhysicalDeviceProperties2Fn::load(&mut load_fn), 
            khr_get_surface_capabilities2: ash::vk::KhrGetSurfaceCapabilities2Fn::load(&mut load_fn), 
            khr_performance_query: ash::vk::KhrPerformanceQueryFn::load(&mut load_fn), 
            khr_surface: ash::vk::KhrSurfaceFn::load(&mut load_fn), 
            khr_swapchain: ash::vk::KhrSwapchainFn::load(&mut load_fn), 
            khr_video_queue: ash::vk::KhrVideoQueueFn::load(&mut load_fn), 
            khr_wayland_surface: ash::vk::KhrWaylandSurfaceFn::load(&mut load_fn), 
            khr_win32_surface: ash::vk::KhrWin32SurfaceFn::load(&mut load_fn), 
            khr_xcb_surface: ash::vk::KhrXcbSurfaceFn::load(&mut load_fn), 
            khr_xlib_surface: ash::vk::KhrXlibSurfaceFn::load(&mut load_fn), 
            ext_acquire_drm_display: ash::vk::ExtAcquireDrmDisplayFn::load(&mut load_fn), 
            ext_acquire_xlib_display: ash::vk::ExtAcquireXlibDisplayFn::load(&mut load_fn), 
            ext_calibrated_timestamps: ash::vk::ExtCalibratedTimestampsFn::load(&mut load_fn),
            ext_debug_report: ash::vk::ExtDebugReportFn::load(&mut load_fn), 
            ext_debug_utils: ash::vk::ExtDebugUtilsFn::load(&mut load_fn), 
            ext_direct_mode_display: ash::vk::ExtDirectModeDisplayFn::load(&mut load_fn), 
            ext_directfb_surface: ash::vk::ExtDirectfbSurfaceFn::load(&mut load_fn), 
            ext_display_surface_counter: ash::vk::ExtDisplaySurfaceCounterFn::load(&mut load_fn), 
            ext_full_screen_exclusive: ash::vk::ExtFullScreenExclusiveFn::load(&mut load_fn), 
            ext_headless_surface: ash::vk::ExtHeadlessSurfaceFn::load(&mut load_fn), 
            ext_metal_surface: ash::vk::ExtMetalSurfaceFn::load(&mut load_fn), 
            ext_sample_locations: ash::vk::ExtSampleLocationsFn::load(&mut load_fn), 
            ext_tooling_info: ash::vk::ExtToolingInfoFn::load(&mut load_fn), 
            fuchsia_imagepipe_surface: ash::vk::FuchsiaImagepipeSurfaceFn::load(&mut load_fn), 
            ggp_stream_descriptor_surface: ash::vk::GgpStreamDescriptorSurfaceFn::load(&mut load_fn), 
            mvk_ios_surface: ash::vk::MvkIosSurfaceFn::load(&mut load_fn), 
            mvk_macos_surface: ash::vk::MvkMacosSurfaceFn::load(&mut load_fn), 
            nn_vi_surface: ash::vk::NnViSurfaceFn::load(&mut load_fn), 
            nv_cooperative_matrix: ash::vk::NvCooperativeMatrixFn::load(&mut load_fn), 
            nv_coverage_reduction_mode: ash::vk::NvCoverageReductionModeFn::load(&mut load_fn), 
            nv_external_memory_capabilities: ash::vk::NvExternalMemoryCapabilitiesFn::load(&mut load_fn), 
            nv_optical_flow: ash::vk::NvOpticalFlowFn::load(&mut load_fn), 
            qnx_screen_surface: ash::vk::QnxScreenSurfaceFn::load(&mut load_fn) 
        }
    }
}